package com.dopaminacrew.backend.repository;

import com.dopaminacrew.backend.model.LoginAudit;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Data access layer for LoginAudit entity.
 * Security Note: Parameterized queries are automatically generated by Spring Data JPA to prevent SQL Injection.
 */
@Repository
public interface LoginAuditRepository extends JpaRepository<LoginAudit, Long> {

    List<LoginAudit> findByEmailAndTimestampAfterOrderByTimestampDesc(String email, LocalDateTime after);

    List<LoginAudit> findByIpAddressAndTimestampAfterOrderByTimestampDesc(String ipAddress, LocalDateTime after);

    List<LoginAudit> findByEmailAndDetallesContainingAndTimestampAfter(String email, String details, LocalDateTime after);

    List<LoginAudit> findAllByOrderByTimestampDesc();
}
